---
  shardable:
    db:
      common:
        user: "postgres"
        password: ""
        host: "127.0.0.1"
        port: "5432"
        pool:
          max: 10
    shards:
      shard_0:
        db: "m3_development_0"
        db_cfg: "common"
      shard_1:
        db: "m3_development_1"
        db_cfg: "common"
  standalone:
    user: "postgres"
    password: ""
    host: "127.0.0.1"
    port: "5432"
    database: "m3_development_extra"