module.exports = {
    activate_item_grade: require('./activateItemGradeCommand'),
    add_achievement: require('./addAchievementCommand'),
    add_sharing: require('./addSharingCommand'),
    buy_booster_pack: require('./buyBoosterPackCommand'),
    buy_chapter_unlocks: require('./buyChapterUnlocksCommand'),
    buy_item_grade: require('./buyItemGradeCommand'),
    buy_life: require('./buyLifeCommand'),
    claim_next_achievement_reward: require('./claimNextAchievementRewardCommand'),
    claim_sharing_reward: require('./claimSharingRewardCommand'),
    finish_level: require('./finishLevelCommand'),
    finish_bonus_level: require('./finishBonusLevelCommand'),
    idkfa: require('./idkfaCommand'),
    like: require('./likeCommand'),
    read_message: require('./readMessageCommand'),
    request_fuel: require('./requestFuelCommand'),
    request_life: require('./requestLifeCommand'),
    send_life: require('./sendLifeCommand'),
    send_help_for_level: require('./sendHelpForLevelCommand'),
    send_message: require('./sendMessageCommand'),
    unlock_chapter: require('./unlockChapterCommand'),
    update_locked_chapter: require('./updateLockedChapterCommand'),
    buy_secret_level_cheat: require('./buySecretLevelCheatCommand'),
    finish_secret_level: require('./finishSecretLevelCommand'),
    update_secret_level_progress: require('./updateSecretLevelProgressCommand')
};
