module.exports = function(server, records) {

    var level = {"background":"back001","board":{"width":9,"height":9},"scores":[1111,11111,111111],"limit":{"moves":50},"objectives":{},"colors":{"easy":{"blue":1,"green":1,"red":1},"normal":{"blue":1,"green":1,"red":1}},"cells":[{"x":0,"y":0,"disabled":true},{"x":0,"y":1,"disabled":true},{"x":0,"y":2,"disabled":true},{"x":0,"y":3,"disabled":true},{"x":0,"y":4,"disabled":true},{"x":0,"y":5,"disabled":true},{"x":0,"y":6,"disabled":true},{"x":0,"y":7,"disabled":true},{"x":0,"y":8,"disabled":true},{"x":1,"y":0,"disabled":true},{"x":1,"y":1,"disabled":true},{"x":1,"y":2,"disabled":true},{"x":1,"y":3,"disabled":true},{"x":1,"y":4,"disabled":true},{"x":1,"y":5,"disabled":true},{"x":1,"y":6,"disabled":true},{"x":1,"y":7,"disabled":true},{"x":1,"y":8,"disabled":true},{"x":2,"y":0,"disabled":true},{"x":2,"y":1,"disabled":true},{"x":2,"y":2,"piece":"green"},{"x":2,"y":3,"piece":"blue"},{"x":2,"y":4,"piece":"green"},{"x":2,"y":5,"piece":"green"},{"x":2,"y":6,"disabled":true},{"x":2,"y":7,"disabled":true},{"x":2,"y":8,"disabled":true},{"x":3,"y":0,"disabled":true},{"x":3,"y":1,"disabled":true},{"x":3,"y":2,"piece":"red"},{"x":3,"y":3,"piece":"blue"},{"x":3,"y":4,"piece":"green"},{"x":3,"y":5,"piece":"green"},{"x":3,"y":6,"disabled":true},{"x":3,"y":7,"disabled":true},{"x":3,"y":8,"disabled":true},{"x":4,"y":0,"disabled":true},{"x":4,"y":1,"disabled":true},{"x":4,"y":2,"piece":"blue"},{"x":4,"y":3,"piece":"green"},{"x":4,"y":4,"piece":"blue"},{"x":4,"y":5,"piece":"blue"},{"x":4,"y":6,"disabled":true},{"x":4,"y":7,"disabled":true},{"x":4,"y":8,"disabled":true},{"x":5,"y":0,"disabled":true},{"x":5,"y":1,"disabled":true},{"x":5,"y":2,"piece":"red"},{"x":5,"y":3,"piece":"blue"},{"x":5,"y":4,"piece":"green"},{"x":5,"y":5,"piece":"green"},{"x":5,"y":6,"disabled":true},{"x":5,"y":7,"disabled":true},{"x":5,"y":8,"disabled":true},{"x":6,"y":0,"disabled":true},{"x":6,"y":1,"disabled":true},{"x":6,"y":2,"piece":"green"},{"x":6,"y":3,"piece":"blue"},{"x":6,"y":4,"piece":"green"},{"x":6,"y":5,"piece":"green"},{"x":6,"y":6,"disabled":true},{"x":6,"y":7,"disabled":true},{"x":6,"y":8,"disabled":true},{"x":7,"y":0,"disabled":true},{"x":7,"y":1,"disabled":true},{"x":7,"y":2,"disabled":true},{"x":7,"y":3,"disabled":true},{"x":7,"y":4,"disabled":true},{"x":7,"y":5,"disabled":true},{"x":7,"y":6,"disabled":true},{"x":7,"y":7,"spawn":true},{"x":7,"y":8,"disabled":true},{"x":8,"y":0,"disabled":true},{"x":8,"y":1,"disabled":true},{"x":8,"y":2,"disabled":true},{"x":8,"y":3,"disabled":true},{"x":8,"y":4,"disabled":true},{"x":8,"y":5,"disabled":true},{"x":8,"y":6,"disabled":true},{"x":8,"y":7,"disabled":true},{"x":8,"y":8,"disabled":true}]};

    var session = server.login({
        user: 'guest',
        password: '123'
    });

    session.insertLevel({name: '123', data: level});
};
